# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://laurajjp.github.io/deck_of_cardsv1/"

git_url = "https://github.com/laurajjp/deck_of_cardsv1/tree/{branch}/"

def custom_doc_links(name): return None
